# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pytubeviewtTlaAB.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QComboBox, QLabel,
    QMainWindow, QMenu, QMenuBar, QPlainTextEdit,
    QPushButton, QSizePolicy, QSlider, QSpinBox,
    QStatusBar, QTabWidget, QTextBrowser, QTextEdit,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(761, 615)
        self.loadImageMenuItem = QAction(MainWindow)
        self.loadImageMenuItem.setObjectName(u"loadImageMenuItem")
        self.saveImageMenuItem = QAction(MainWindow)
        self.saveImageMenuItem.setObjectName(u"saveImageMenuItem")
        self.saveOverlayMenuItem = QAction(MainWindow)
        self.saveOverlayMenuItem.setObjectName(u"saveOverlayMenuItem")
        self.saveModelsMenuItem = QAction(MainWindow)
        self.saveModelsMenuItem.setObjectName(u"saveModelsMenuItem")
        self.actionLoad_Scene = QAction(MainWindow)
        self.actionLoad_Scene.setObjectName(u"actionLoad_Scene")
        self.actionSave_Scene = QAction(MainWindow)
        self.actionSave_Scene.setObjectName(u"actionSave_Scene")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.view2DSliceSlider = QSlider(self.centralwidget)
        self.view2DSliceSlider.setObjectName(u"view2DSliceSlider")
        self.view2DSliceSlider.setGeometry(QRect(370, 10, 22, 311))
        self.view2DSliceSlider.setOrientation(Qt.Vertical)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(170, 400, 571, 171))
        self.tabView = QWidget()
        self.tabView.setObjectName(u"tabView")
        self.verticalLayoutWidget_3 = QWidget(self.tabView)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(9, 9, 541, 121))
        self.tabViewLayout = QVBoxLayout(self.verticalLayoutWidget_3)
        self.tabViewLayout.setObjectName(u"tabViewLayout")
        self.tabViewLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget.addTab(self.tabView, "")
        self.preprocessTab = QWidget()
        self.preprocessTab.setObjectName(u"preprocessTab")
        self.preprocMedianFilterButton = QPushButton(self.preprocessTab)
        self.preprocMedianFilterButton.setObjectName(u"preprocMedianFilterButton")
        self.preprocMedianFilterButton.setGeometry(QRect(230, 20, 121, 24))
        self.preprocMedianRadiusBox = QSpinBox(self.preprocessTab)
        self.preprocMedianRadiusBox.setObjectName(u"preprocMedianRadiusBox")
        self.preprocMedianRadiusBox.setGeometry(QRect(360, 20, 42, 22))
        self.preprocLowResIsoButton = QPushButton(self.preprocessTab)
        self.preprocLowResIsoButton.setObjectName(u"preprocLowResIsoButton")
        self.preprocLowResIsoButton.setGeometry(QRect(20, 20, 181, 24))
        self.preprocHighResIsoButton = QPushButton(self.preprocessTab)
        self.preprocHighResIsoButton.setObjectName(u"preprocHighResIsoButton")
        self.preprocHighResIsoButton.setGeometry(QRect(20, 50, 181, 24))
        self.tabWidget.addTab(self.preprocessTab, "")
        self.lungTab = QWidget()
        self.lungTab.setObjectName(u"lungTab")
        self.pushButton = QPushButton(self.lungTab)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(340, 10, 91, 24))
        self.label = QLabel(self.lungTab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 61, 16))
        self.textBrowser = QTextBrowser(self.lungTab)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(70, 10, 261, 121))
        self.pushButton_2 = QPushButton(self.lungTab)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(400, 100, 141, 24))
        self.tabWidget.addTab(self.lungTab, "")
        self.view2DSliceText = QPlainTextEdit(self.centralwidget)
        self.view2DSliceText.setObjectName(u"view2DSliceText")
        self.view2DSliceText.setGeometry(QRect(365, 330, 31, 21))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view2DSliceText.sizePolicy().hasHeightForWidth())
        self.view2DSliceText.setSizePolicy(sizePolicy)
        self.view2DSliceText.setMinimumSize(QSize(31, 21))
        self.view2DSliceText.setBaseSize(QSize(31, 21))
        font = QFont()
        font.setPointSize(7)
        self.view2DSliceText.setFont(font)
        self.view2DSliceText.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.view2DSliceText.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.view2DSliceText.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.view2DSliceText.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.objectComboBox = QComboBox(self.centralwidget)
        self.objectComboBox.setObjectName(u"objectComboBox")
        self.objectComboBox.setGeometry(QRect(60, 407, 101, 26))
        self.objectLabel = QLabel(self.centralwidget)
        self.objectLabel.setObjectName(u"objectLabel")
        self.objectLabel.setGeometry(QRect(10, 407, 49, 20))
        self.objectInfoLabel = QLabel(self.centralwidget)
        self.objectInfoLabel.setObjectName(u"objectInfoLabel")
        self.objectInfoLabel.setGeometry(QRect(10, 520, 49, 16))
        self.view2DXYButton = QPushButton(self.centralwidget)
        self.view2DXYButton.setObjectName(u"view2DXYButton")
        self.view2DXYButton.setGeometry(QRect(10, 370, 61, 24))
        self.view2DXZButton = QPushButton(self.centralwidget)
        self.view2DXZButton.setObjectName(u"view2DXZButton")
        self.view2DXZButton.setGeometry(QRect(80, 370, 61, 24))
        self.view2DYZButton = QPushButton(self.centralwidget)
        self.view2DYZButton.setObjectName(u"view2DYZButton")
        self.view2DYZButton.setGeometry(QRect(150, 370, 61, 24))
        self.view2DOverlayOpacitySlider = QSlider(self.centralwidget)
        self.view2DOverlayOpacitySlider.setObjectName(u"view2DOverlayOpacitySlider")
        self.view2DOverlayOpacitySlider.setGeometry(QRect(270, 374, 91, 16))
        self.view2DOverlayOpacitySlider.setOrientation(Qt.Horizontal)
        self.view2DOverlayOpacityLabel = QLabel(self.centralwidget)
        self.view2DOverlayOpacityLabel.setObjectName(u"view2DOverlayOpacityLabel")
        self.view2DOverlayOpacityLabel.setGeometry(QRect(230, 360, 51, 41))
        self.view2DOverlayOpacityLabel.setFont(font)
        self.view2DOverlayOpacityLabel.setWordWrap(True)
        self.objectColorLabel = QLabel(self.centralwidget)
        self.objectColorLabel.setObjectName(u"objectColorLabel")
        self.objectColorLabel.setGeometry(QRect(10, 439, 49, 24))
        self.objectColorComboBox = QComboBox(self.centralwidget)
        self.objectColorComboBox.setObjectName(u"objectColorComboBox")
        self.objectColorComboBox.setGeometry(QRect(60, 437, 101, 26))
        self.objectFormLabel = QLabel(self.centralwidget)
        self.objectFormLabel.setObjectName(u"objectFormLabel")
        self.objectFormLabel.setGeometry(QRect(10, 490, 49, 20))
        self.objectOpacityLabel = QLabel(self.centralwidget)
        self.objectOpacityLabel.setObjectName(u"objectOpacityLabel")
        self.objectOpacityLabel.setGeometry(QRect(10, 466, 49, 20))
        self.objectOpacitySlider = QSlider(self.centralwidget)
        self.objectOpacitySlider.setObjectName(u"objectOpacitySlider")
        self.objectOpacitySlider.setGeometry(QRect(60, 467, 101, 20))
        self.objectOpacitySlider.setOrientation(Qt.Horizontal)
        self.objectFormComboBox = QComboBox(self.centralwidget)
        self.objectFormComboBox.setObjectName(u"objectFormComboBox")
        self.objectFormComboBox.setGeometry(QRect(60, 487, 101, 26))
        self.objectInfoText = QTextEdit(self.centralwidget)
        self.objectInfoText.setObjectName(u"objectInfoText")
        self.objectInfoText.setGeometry(QRect(60, 520, 101, 51))
        self.objectInfoText.setFont(font)
        self.objectInfoText.setMouseTracking(False)
        self.objectInfoText.setAcceptDrops(False)
        self.objectInfoText.setUndoRedoEnabled(False)
        self.objectInfoText.setReadOnly(True)
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 10, 351, 351))
        self.view2DWidget = QVBoxLayout(self.verticalLayoutWidget)
        self.view2DWidget.setObjectName(u"view2DWidget")
        self.view2DWidget.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutWidget_2 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(400, 10, 351, 351))
        self.view3DWidget = QVBoxLayout(self.verticalLayoutWidget_2)
        self.view3DWidget.setObjectName(u"view3DWidget")
        self.view3DWidget.setContentsMargins(0, 0, 0, 0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 761, 22))
        self.menuMIDAS_Qt = QMenu(self.menubar)
        self.menuMIDAS_Qt.setObjectName(u"menuMIDAS_Qt")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuMIDAS_Qt.menuAction())
        self.menuMIDAS_Qt.addAction(self.actionLoad_Scene)
        self.menuMIDAS_Qt.addAction(self.loadImageMenuItem)
        self.menuMIDAS_Qt.addSeparator()
        self.menuMIDAS_Qt.addAction(self.actionSave_Scene)
        self.menuMIDAS_Qt.addAction(self.saveImageMenuItem)
        self.menuMIDAS_Qt.addSeparator()
        self.menuMIDAS_Qt.addAction(self.saveOverlayMenuItem)
        self.menuMIDAS_Qt.addAction(self.saveModelsMenuItem)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.loadImageMenuItem.setText(QCoreApplication.translate("MainWindow", u"Load Image", None))
        self.saveImageMenuItem.setText(QCoreApplication.translate("MainWindow", u"Save Image", None))
        self.saveOverlayMenuItem.setText(QCoreApplication.translate("MainWindow", u"Save Overlay", None))
        self.saveModelsMenuItem.setText(QCoreApplication.translate("MainWindow", u"Save Models", None))
        self.actionLoad_Scene.setText(QCoreApplication.translate("MainWindow", u"Load Scene", None))
        self.actionSave_Scene.setText(QCoreApplication.translate("MainWindow", u"Save Scene", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabView), QCoreApplication.translate("MainWindow", u"View", None))
        self.preprocMedianFilterButton.setText(QCoreApplication.translate("MainWindow", u"Median Filter", None))
        self.preprocLowResIsoButton.setText(QCoreApplication.translate("MainWindow", u"Make Low-Res Isotropic", None))
        self.preprocHighResIsoButton.setText(QCoreApplication.translate("MainWindow", u"Make High-Res Isotropic", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preprocessTab), QCoreApplication.translate("MainWindow", u"PreProcess", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Force Load AI", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"AI Status:", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Segment Lungs", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lungTab), QCoreApplication.translate("MainWindow", u"Lung", None))
        self.view2DSliceText.setPlainText(QCoreApplication.translate("MainWindow", u"100", None))
#if QT_CONFIG(accessibility)
        self.objectComboBox.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.objectComboBox.setCurrentText("")
        self.objectLabel.setText(QCoreApplication.translate("MainWindow", u"Object:", None))
        self.objectInfoLabel.setText(QCoreApplication.translate("MainWindow", u"Info:", None))
        self.view2DXYButton.setText(QCoreApplication.translate("MainWindow", u"XY", None))
        self.view2DXZButton.setText(QCoreApplication.translate("MainWindow", u"XZ", None))
        self.view2DYZButton.setText(QCoreApplication.translate("MainWindow", u"YZ", None))
        self.view2DOverlayOpacityLabel.setText(QCoreApplication.translate("MainWindow", u"Overlay Opacity", None))
        self.objectColorLabel.setText(QCoreApplication.translate("MainWindow", u"Color:", None))
#if QT_CONFIG(accessibility)
        self.objectColorComboBox.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.objectColorComboBox.setCurrentText("")
        self.objectFormLabel.setText(QCoreApplication.translate("MainWindow", u"Form:", None))
        self.objectOpacityLabel.setText(QCoreApplication.translate("MainWindow", u"Opacity:", None))
#if QT_CONFIG(accessibility)
        self.objectFormComboBox.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.objectFormComboBox.setCurrentText("")
        self.menuMIDAS_Qt.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    # retranslateUi

