# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pytubeviewpKzIqc.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QHeaderView,
    QLabel, QLayout, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QSlider,
    QStatusBar, QTabWidget, QTableWidget, QTableWidgetItem,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1052, 632)
        self.loadImageMenuItem = QAction(MainWindow)
        self.loadImageMenuItem.setObjectName(u"loadImageMenuItem")
        self.saveImageMenuItem = QAction(MainWindow)
        self.saveImageMenuItem.setObjectName(u"saveImageMenuItem")
        self.saveOverlayMenuItem = QAction(MainWindow)
        self.saveOverlayMenuItem.setObjectName(u"saveOverlayMenuItem")
        self.saveModelsMenuItem = QAction(MainWindow)
        self.saveModelsMenuItem.setObjectName(u"saveModelsMenuItem")
        self.loadSceneMenuItem = QAction(MainWindow)
        self.loadSceneMenuItem.setObjectName(u"loadSceneMenuItem")
        self.saveSceneMenuItem = QAction(MainWindow)
        self.saveSceneMenuItem.setObjectName(u"saveSceneMenuItem")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(220, 400, 531, 171))
        self.visualizationPanel = QWidget()
        self.visualizationPanel.setObjectName(u"visualizationPanel")
        self.verticalLayoutWidget_3 = QWidget(self.visualizationPanel)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(9, 9, 511, 131))
        self.visualizationPanelLayout = QVBoxLayout(self.verticalLayoutWidget_3)
        self.visualizationPanelLayout.setObjectName(u"visualizationPanelLayout")
        self.visualizationPanelLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget.addTab(self.visualizationPanel, "")
        self.preProcessPanel = QWidget()
        self.preProcessPanel.setObjectName(u"preProcessPanel")
        self.verticalLayoutWidget_7 = QWidget(self.preProcessPanel)
        self.verticalLayoutWidget_7.setObjectName(u"verticalLayoutWidget_7")
        self.verticalLayoutWidget_7.setGeometry(QRect(10, 10, 511, 131))
        self.preProcessPanelLayout = QVBoxLayout(self.verticalLayoutWidget_7)
        self.preProcessPanelLayout.setObjectName(u"preProcessPanelLayout")
        self.preProcessPanelLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget.addTab(self.preProcessPanel, "")
        self.lungAIPanel = QWidget()
        self.lungAIPanel.setObjectName(u"lungAIPanel")
        self.verticalLayoutWidget_6 = QWidget(self.lungAIPanel)
        self.verticalLayoutWidget_6.setObjectName(u"verticalLayoutWidget_6")
        self.verticalLayoutWidget_6.setGeometry(QRect(10, 10, 511, 131))
        self.lungAIPanelLayout = QVBoxLayout(self.verticalLayoutWidget_6)
        self.lungAIPanelLayout.setObjectName(u"lungAIPanelLayout")
        self.lungAIPanelLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget.addTab(self.lungAIPanel, "")
        self.objectNameComboBox = QComboBox(self.centralwidget)
        self.objectNameComboBox.setObjectName(u"objectNameComboBox")
        self.objectNameComboBox.setGeometry(QRect(50, 407, 111, 26))
        self.objectNameLabel = QLabel(self.centralwidget)
        self.objectNameLabel.setObjectName(u"objectNameLabel")
        self.objectNameLabel.setGeometry(QRect(10, 410, 49, 20))
        self.objectColorLabel = QLabel(self.centralwidget)
        self.objectColorLabel.setObjectName(u"objectColorLabel")
        self.objectColorLabel.setGeometry(QRect(30, 497, 61, 24))
        self.objectColorComboBox = QComboBox(self.centralwidget)
        self.objectColorComboBox.setObjectName(u"objectColorComboBox")
        self.objectColorComboBox.setGeometry(QRect(100, 497, 101, 26))
        self.objectOpacityLabel = QLabel(self.centralwidget)
        self.objectOpacityLabel.setObjectName(u"objectOpacityLabel")
        self.objectOpacityLabel.setGeometry(QRect(30, 526, 51, 20))
        self.objectOpacitySlider = QSlider(self.centralwidget)
        self.objectOpacitySlider.setObjectName(u"objectOpacitySlider")
        self.objectOpacitySlider.setGeometry(QRect(100, 530, 101, 20))
        font = QFont()
        font.setPointSize(5)
        self.objectOpacitySlider.setFont(font)
        self.objectOpacitySlider.setMaximum(100)
        self.objectOpacitySlider.setValue(50)
        self.objectOpacitySlider.setOrientation(Qt.Horizontal)
        self.verticalLayoutWidget_2 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(400, 10, 351, 391))
        self.view3DPanelLayout = QVBoxLayout(self.verticalLayoutWidget_2)
        self.view3DPanelLayout.setObjectName(u"view3DPanelLayout")
        self.view3DPanelLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.view3DPanelLayout.setContentsMargins(0, 0, 0, 0)
        self.tableWidget = QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(760, 10, 281, 221))
        self.verticalLayoutWidget_4 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(760, 240, 281, 121))
        self.screenCapturePanelLayout = QVBoxLayout(self.verticalLayoutWidget_4)
        self.screenCapturePanelLayout.setObjectName(u"screenCapturePanelLayout")
        self.screenCapturePanelLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutWidget_5 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setObjectName(u"verticalLayoutWidget_5")
        self.verticalLayoutWidget_5.setGeometry(QRect(760, 370, 281, 201))
        self.chatPanelLayout = QVBoxLayout(self.verticalLayoutWidget_5)
        self.chatPanelLayout.setObjectName(u"chatPanelLayout")
        self.chatPanelLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutWidget_8 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setObjectName(u"verticalLayoutWidget_8")
        self.verticalLayoutWidget_8.setGeometry(QRect(10, 10, 391, 391))
        self.view2DPanelLayout = QVBoxLayout(self.verticalLayoutWidget_8)
        self.view2DPanelLayout.setObjectName(u"view2DPanelLayout")
        self.view2DPanelLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.view2DPanelLayout.setContentsMargins(0, 0, 0, 0)
        self.objectDeleteButton = QPushButton(self.centralwidget)
        self.objectDeleteButton.setObjectName(u"objectDeleteButton")
        self.objectDeleteButton.setGeometry(QRect(170, 407, 41, 24))
        font1 = QFont()
        font1.setPointSize(7)
        self.objectDeleteButton.setFont(font1)
        self.objectColorByLabel = QLabel(self.centralwidget)
        self.objectColorByLabel.setObjectName(u"objectColorByLabel")
        self.objectColorByLabel.setGeometry(QRect(30, 467, 71, 24))
        self.objectColorByComboBox = QComboBox(self.centralwidget)
        self.objectColorByComboBox.setObjectName(u"objectColorByComboBox")
        self.objectColorByComboBox.setGeometry(QRect(100, 467, 101, 26))
        self.objectHightlightSelectedCheckBox = QCheckBox(self.centralwidget)
        self.objectHightlightSelectedCheckBox.setObjectName(u"objectHightlightSelectedCheckBox")
        self.objectHightlightSelectedCheckBox.setGeometry(QRect(20, 440, 71, 20))
        font2 = QFont()
        font2.setPointSize(9)
        self.objectHightlightSelectedCheckBox.setFont(font2)
        self.objectHightlightSelectedCheckBox.setChecked(True)
        self.objectPropertiesToAllButton = QPushButton(self.centralwidget)
        self.objectPropertiesToAllButton.setObjectName(u"objectPropertiesToAllButton")
        self.objectPropertiesToAllButton.setGeometry(QRect(160, 554, 41, 24))
        self.objectPropertiesToAllButton.setFont(font1)
        self.objectPropertiesToChildrenButton = QPushButton(self.centralwidget)
        self.objectPropertiesToChildrenButton.setObjectName(u"objectPropertiesToChildrenButton")
        self.objectPropertiesToChildrenButton.setGeometry(QRect(100, 554, 41, 24))
        self.objectPropertiesToChildrenButton.setFont(font1)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 556, 49, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1052, 22))
        self.menuMIDAS_Qt = QMenu(self.menubar)
        self.menuMIDAS_Qt.setObjectName(u"menuMIDAS_Qt")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuMIDAS_Qt.menuAction())
        self.menuMIDAS_Qt.addAction(self.loadSceneMenuItem)
        self.menuMIDAS_Qt.addAction(self.loadImageMenuItem)
        self.menuMIDAS_Qt.addSeparator()
        self.menuMIDAS_Qt.addAction(self.saveSceneMenuItem)
        self.menuMIDAS_Qt.addAction(self.saveImageMenuItem)
        self.menuMIDAS_Qt.addSeparator()
        self.menuMIDAS_Qt.addAction(self.saveOverlayMenuItem)
        self.menuMIDAS_Qt.addAction(self.saveModelsMenuItem)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.loadImageMenuItem.setText(QCoreApplication.translate("MainWindow", u"Load Image", None))
        self.saveImageMenuItem.setText(QCoreApplication.translate("MainWindow", u"Save Image", None))
        self.saveOverlayMenuItem.setText(QCoreApplication.translate("MainWindow", u"Save Overlay", None))
        self.saveModelsMenuItem.setText(QCoreApplication.translate("MainWindow", u"Save Models", None))
        self.loadSceneMenuItem.setText(QCoreApplication.translate("MainWindow", u"Load Scene", None))
        self.saveSceneMenuItem.setText(QCoreApplication.translate("MainWindow", u"Save Scene", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.visualizationPanel), QCoreApplication.translate("MainWindow", u"Visualization", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preProcessPanel), QCoreApplication.translate("MainWindow", u"PreProcess", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lungAIPanel), QCoreApplication.translate("MainWindow", u"Lung AI", None))
#if QT_CONFIG(accessibility)
        self.objectNameComboBox.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.objectNameComboBox.setCurrentText("")
        self.objectNameLabel.setText(QCoreApplication.translate("MainWindow", u"Object:", None))
        self.objectColorLabel.setText(QCoreApplication.translate("MainWindow", u"Solid Color:", None))
#if QT_CONFIG(accessibility)
        self.objectColorComboBox.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.objectColorComboBox.setCurrentText("")
        self.objectOpacityLabel.setText(QCoreApplication.translate("MainWindow", u"Opacity:", None))
        self.objectDeleteButton.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.objectColorByLabel.setText(QCoreApplication.translate("MainWindow", u"Color by:", None))
#if QT_CONFIG(accessibility)
        self.objectColorByComboBox.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.objectColorByComboBox.setCurrentText("")
        self.objectHightlightSelectedCheckBox.setText(QCoreApplication.translate("MainWindow", u"Highlight", None))
        self.objectPropertiesToAllButton.setText(QCoreApplication.translate("MainWindow", u"All", None))
        self.objectPropertiesToChildrenButton.setText(QCoreApplication.translate("MainWindow", u"Children", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Apply to:", None))
        self.menuMIDAS_Qt.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    # retranslateUi

